baseURL = "https://jorgelabs.com"
disqusShortname = ""
languageCode = "en-us"
paginate = "5"
summaryLength = "10"
theme = "northendlab-hugo"
title = "Jorge Labs"
[[menu.footer]]
URL = "contact"
name = "Contact"
weight = 1
[[menu.footer]]
URL = "about"
name = "About"
weight = 1
[[menu.footer]]
URL = "experience"
name = "Experience"
weight = 1
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 1
[[menu.main]]
URL = "about"
name = "About"
weight = 1
[[menu.main]]
URL = "experience"
name = "Experience"
weight = 1
[outputs]
home = ["HTML", "AMP", "RSS", "JSON"]
[params]
author = "Jorge Arteaga"
contact_form_action = "#"
copyright = "&copy; 2020 [JorgeLabs](https://jorgelabs.com)"
description = "Personal site of Jorge Jr. Arteaga Carvalho, a full-stack web developer specialized in Ruby on Rails and React.js"
google_analitycs_id = ""
google_tag_manager = ""
home = "Home"
logo = "images/logo.svg"
[params.banner]
bgImage = "images/banner/banner-bg.svg"
image = "images/profile_pic_desktop.png"
title = "Hi, I'm Jorge Arteaga. <br> I'm a software developer with 4 years of experience."
[params.blog]
enable = false
[params.cta]
description = "Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus."
enable = false
image = "images/hugo-muscot.svg"
title = "Get the best hugo templates"
[params.cta.button]
enable = false
label = "Visit Here"
link = "https://gethugothemes.com/shop/"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[params.preloader]
enable = true
preloader = ""
[params.search]
enable = false
[[params.social]]
icon = "ti-github"
link = "https://github.com/jorge8989"
[[params.social]]
icon = "ti-linkedin"
link = "https://www.linkedin.com/in/jorge-arteaga-carvalho-618717125/"
